apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-id-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-id
  template:
    metadata:
      labels:
        app: student-id
    spec:
      containers:
      - name: student-id
        image: wenan1234/student-id-web:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: student-id-service
spec:
  type: NodePort
  selector:
    app: student-id
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080